version: "3"
services:
  client:
    build: "./client"
    ports:
      - "8080:80"
  server:
    build: "./server"
    ports:
      - "5000:5000"
    environment:
      ONLINE_EDITOR_DATABASE_HOST: "database"
      ONLINE_EDITOR_DATABASE_DBNAME: "studres"
      ONLINE_EDITOR_DATABASE_USERNAME: "postgres"
      ONLINE_EDITOR_DATABASE_PASSWORD: "postgres"

  database:
    build: "./database"
    ports:
      - "5432:5432"